// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewStaffInput struct {
	FirstName  string  `json:"firstName"`
	LastName   string  `json:"lastName"`
	Email      string  `json:"email"`
	WorkNumber *string `json:"workNumber,omitempty"`
	Role       string  `json:"role"`
	Department string  `json:"department"`
	Salary     float64 `json:"salary"`
}

type Project struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Department  string  `json:"department"`
	Budget      float64 `json:"budget"`
}

type Query struct {
}

type Staff struct {
	ID         string     `json:"id"`
	FirstName  string     `json:"firstName"`
	LastName   string     `json:"lastName"`
	Email      string     `json:"email"`
	WorkNumber *string    `json:"workNumber,omitempty"`
	Role       string     `json:"role"`
	Department string     `json:"department"`
	Salary     float64    `json:"salary"`
	Projects   []*Project `json:"projects,omitempty"`
}
